name: CMake CI

on:
  push:
    branches:
          - '**' # matches every branch
  pull_request:
    branches:
          - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install gtest
      run: sudo apt-get install libgtest-dev
      
    - uses: actions/checkout@v4

    - name: ls
      run: ls
    - name: pwd
      run: pwd
      
    - name: Configure CMake
      working-directory: ${{github.workspace}}
      run: cmake -S . -B build
      
    - name: Build
      run: cmake --build build

    - name: Test
      working-directory: build
      run: ctest
