name: CMake CI

on:
  push:
    branches:
          - '**' # matches every branch
  pull_request:
    branches:
          - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install gtest
      run: sudo apt-get install libgtest-dev
      
    - uses: actions/checkout@v4

    - name: ls
      run: ls
      
    - name: Configure CMake
      run: cmake -S ${{github.workspace}} -B build
      
    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest
